### ISSUE TITLE
Muted role request for music

### ISSUE THREAD

**Issue by zztyo** [Seklfreak/Robyul-Red-DiscordBot#8]
Can we add a role that basically disables your ability to queue songs on robyul (for people who like to spam annoying af songs when theres actually people in VC), or have them unable to queue music it the number of people in VC is above a certain threshold if the former is too harsh

**Comment by Seklfreak** [comment]
Done in 3a78ba32a8d0299b135d4d0fa21be30689afb8fc. Thank you!
